version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Rocket.Libraries.Emailing.sln && dotnet publish ./Rocket.Libraries.Emailing.sln -c Release -o -r linux-x64 ./obj/Docker/publish"
